package life.drift.movie.mapper;

import java.util.List;
import life.drift.movie.model.Review;
import life.drift.movie.model.ReviewExample;
import org.apache.ibatis.annotations.Param;

public interface ReviewMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table review
     *
     * @mbg.generated Fri Apr 17 00:08:01 GMT+08:00 2020
     */
    long countByExample(ReviewExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table review
     *
     * @mbg.generated Fri Apr 17 00:08:01 GMT+08:00 2020
     */
    int deleteByExample(ReviewExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table review
     *
     * @mbg.generated Fri Apr 17 00:08:01 GMT+08:00 2020
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table review
     *
     * @mbg.generated Fri Apr 17 00:08:01 GMT+08:00 2020
     */
    int insert(Review record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table review
     *
     * @mbg.generated Fri Apr 17 00:08:01 GMT+08:00 2020
     */
    int insertSelective(Review record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table review
     *
     * @mbg.generated Fri Apr 17 00:08:01 GMT+08:00 2020
     */
    List<Review> selectByExampleWithBLOBs(ReviewExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table review
     *
     * @mbg.generated Fri Apr 17 00:08:01 GMT+08:00 2020
     */
    List<Review> selectByExample(ReviewExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table review
     *
     * @mbg.generated Fri Apr 17 00:08:01 GMT+08:00 2020
     */
    Review selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table review
     *
     * @mbg.generated Fri Apr 17 00:08:01 GMT+08:00 2020
     */
    int updateByExampleSelective(@Param("record") Review record, @Param("example") ReviewExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table review
     *
     * @mbg.generated Fri Apr 17 00:08:01 GMT+08:00 2020
     */
    int updateByExampleWithBLOBs(@Param("record") Review record, @Param("example") ReviewExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table review
     *
     * @mbg.generated Fri Apr 17 00:08:01 GMT+08:00 2020
     */
    int updateByExample(@Param("record") Review record, @Param("example") ReviewExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table review
     *
     * @mbg.generated Fri Apr 17 00:08:01 GMT+08:00 2020
     */
    int updateByPrimaryKeySelective(Review record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table review
     *
     * @mbg.generated Fri Apr 17 00:08:01 GMT+08:00 2020
     */
    int updateByPrimaryKeyWithBLOBs(Review record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table review
     *
     * @mbg.generated Fri Apr 17 00:08:01 GMT+08:00 2020
     */
    int updateByPrimaryKey(Review record);
}