package life.drift.movie.model;

import java.util.Date;

public class Movie {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column film.id
     *
     * @mbg.generated Fri Apr 17 00:08:01 GMT+08:00 2020
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column film.movie_name
     *
     * @mbg.generated Fri Apr 17 00:08:01 GMT+08:00 2020
     */
    private String movieName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column film.movie_avatar
     *
     * @mbg.generated Fri Apr 17 00:08:01 GMT+08:00 2020
     */
    private String movieAvatar;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column film.director
     *
     * @mbg.generated Fri Apr 17 00:08:01 GMT+08:00 2020
     */
    private String director;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column film.actor
     *
     * @mbg.generated Fri Apr 17 00:08:01 GMT+08:00 2020
     */
    private String actor;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column film.country
     *
     * @mbg.generated Fri Apr 17 00:08:01 GMT+08:00 2020
     */
    private String country;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column film.score
     *
     * @mbg.generated Fri Apr 17 00:08:01 GMT+08:00 2020
     */
    private Double score;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column film.category
     *
     * @mbg.generated Fri Apr 17 00:08:01 GMT+08:00 2020
     */
    private String category;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column film.show_time
     *
     * @mbg.generated Fri Apr 17 00:08:01 GMT+08:00 2020
     */
    private Date showTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column film.movie_time
     *
     * @mbg.generated Fri Apr 17 00:08:01 GMT+08:00 2020
     */
    private Long movieTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column film.comment_count
     *
     * @mbg.generated Fri Apr 17 00:08:01 GMT+08:00 2020
     */
    private Long commentCount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column film.movie_create
     *
     * @mbg.generated Fri Apr 17 00:08:01 GMT+08:00 2020
     */
    private Date movieCreate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column film.movie_modified
     *
     * @mbg.generated Fri Apr 17 00:08:01 GMT+08:00 2020
     */
    private Date movieModified;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column film.movie_content
     *
     * @mbg.generated Fri Apr 17 00:08:01 GMT+08:00 2020
     */
    private String movieContent;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column film.id
     *
     * @return the value of film.id
     *
     * @mbg.generated Fri Apr 17 00:08:01 GMT+08:00 2020
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column film.id
     *
     * @param id the value for film.id
     *
     * @mbg.generated Fri Apr 17 00:08:01 GMT+08:00 2020
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column film.movie_name
     *
     * @return the value of film.movie_name
     *
     * @mbg.generated Fri Apr 17 00:08:01 GMT+08:00 2020
     */
    public String getMovieName() {
        return movieName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column film.movie_name
     *
     * @param movieName the value for film.movie_name
     *
     * @mbg.generated Fri Apr 17 00:08:01 GMT+08:00 2020
     */
    public void setMovieName(String movieName) {
        this.movieName = movieName == null ? null : movieName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column film.movie_avatar
     *
     * @return the value of film.movie_avatar
     *
     * @mbg.generated Fri Apr 17 00:08:01 GMT+08:00 2020
     */
    public String getMovieAvatar() {
        return movieAvatar;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column film.movie_avatar
     *
     * @param movieAvatar the value for film.movie_avatar
     *
     * @mbg.generated Fri Apr 17 00:08:01 GMT+08:00 2020
     */
    public void setMovieAvatar(String movieAvatar) {
        this.movieAvatar = movieAvatar == null ? null : movieAvatar.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column film.director
     *
     * @return the value of film.director
     *
     * @mbg.generated Fri Apr 17 00:08:01 GMT+08:00 2020
     */
    public String getDirector() {
        return director;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column film.director
     *
     * @param director the value for film.director
     *
     * @mbg.generated Fri Apr 17 00:08:01 GMT+08:00 2020
     */
    public void setDirector(String director) {
        this.director = director == null ? null : director.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column film.actor
     *
     * @return the value of film.actor
     *
     * @mbg.generated Fri Apr 17 00:08:01 GMT+08:00 2020
     */
    public String getActor() {
        return actor;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column film.actor
     *
     * @param actor the value for film.actor
     *
     * @mbg.generated Fri Apr 17 00:08:01 GMT+08:00 2020
     */
    public void setActor(String actor) {
        this.actor = actor == null ? null : actor.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column film.country
     *
     * @return the value of film.country
     *
     * @mbg.generated Fri Apr 17 00:08:01 GMT+08:00 2020
     */
    public String getCountry() {
        return country;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column film.country
     *
     * @param country the value for film.country
     *
     * @mbg.generated Fri Apr 17 00:08:01 GMT+08:00 2020
     */
    public void setCountry(String country) {
        this.country = country == null ? null : country.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column film.score
     *
     * @return the value of film.score
     *
     * @mbg.generated Fri Apr 17 00:08:01 GMT+08:00 2020
     */
    public Double getScore() {
        return score;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column film.score
     *
     * @param score the value for film.score
     *
     * @mbg.generated Fri Apr 17 00:08:01 GMT+08:00 2020
     */
    public void setScore(Double score) {
        this.score = score;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column film.category
     *
     * @return the value of film.category
     *
     * @mbg.generated Fri Apr 17 00:08:01 GMT+08:00 2020
     */
    public String getCategory() {
        return category;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column film.category
     *
     * @param category the value for film.category
     *
     * @mbg.generated Fri Apr 17 00:08:01 GMT+08:00 2020
     */
    public void setCategory(String category) {
        this.category = category == null ? null : category.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column film.show_time
     *
     * @return the value of film.show_time
     *
     * @mbg.generated Fri Apr 17 00:08:01 GMT+08:00 2020
     */
    public Date getShowTime() {
        return showTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column film.show_time
     *
     * @param showTime the value for film.show_time
     *
     * @mbg.generated Fri Apr 17 00:08:01 GMT+08:00 2020
     */
    public void setShowTime(Date showTime) {
        this.showTime = showTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column film.movie_time
     *
     * @return the value of film.movie_time
     *
     * @mbg.generated Fri Apr 17 00:08:01 GMT+08:00 2020
     */
    public Long getMovieTime() {
        return movieTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column film.movie_time
     *
     * @param movieTime the value for film.movie_time
     *
     * @mbg.generated Fri Apr 17 00:08:01 GMT+08:00 2020
     */
    public void setMovieTime(Long movieTime) {
        this.movieTime = movieTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column film.comment_count
     *
     * @return the value of film.comment_count
     *
     * @mbg.generated Fri Apr 17 00:08:01 GMT+08:00 2020
     */
    public Long getCommentCount() {
        return commentCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column film.comment_count
     *
     * @param commentCount the value for film.comment_count
     *
     * @mbg.generated Fri Apr 17 00:08:01 GMT+08:00 2020
     */
    public void setCommentCount(Long commentCount) {
        this.commentCount = commentCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column film.movie_create
     *
     * @return the value of film.movie_create
     *
     * @mbg.generated Fri Apr 17 00:08:01 GMT+08:00 2020
     */
    public Date getMovieCreate() {
        return movieCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column film.movie_create
     *
     * @param movieCreate the value for film.movie_create
     *
     * @mbg.generated Fri Apr 17 00:08:01 GMT+08:00 2020
     */
    public void setMovieCreate(Date movieCreate) {
        this.movieCreate = movieCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column film.movie_modified
     *
     * @return the value of film.movie_modified
     *
     * @mbg.generated Fri Apr 17 00:08:01 GMT+08:00 2020
     */
    public Date getMovieModified() {
        return movieModified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column film.movie_modified
     *
     * @param movieModified the value for film.movie_modified
     *
     * @mbg.generated Fri Apr 17 00:08:01 GMT+08:00 2020
     */
    public void setMovieModified(Date movieModified) {
        this.movieModified = movieModified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column film.movie_content
     *
     * @return the value of film.movie_content
     *
     * @mbg.generated Fri Apr 17 00:08:01 GMT+08:00 2020
     */
    public String getMovieContent() {
        return movieContent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column film.movie_content
     *
     * @param movieContent the value for film.movie_content
     *
     * @mbg.generated Fri Apr 17 00:08:01 GMT+08:00 2020
     */
    public void setMovieContent(String movieContent) {
        this.movieContent = movieContent == null ? null : movieContent.trim();
    }
}