package life.drift.movie.model;

import java.util.Date;

public class Review {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column review.id
     *
     * @mbg.generated Fri May 01 17:26:02 GMT+08:00 2020
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column review.user_id
     *
     * @mbg.generated Fri May 01 17:26:02 GMT+08:00 2020
     */
    private Long userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column review.movie_id
     *
     * @mbg.generated Fri May 01 17:26:02 GMT+08:00 2020
     */
    private Long movieId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column review.is_selected
     *
     * @mbg.generated Fri May 01 17:26:02 GMT+08:00 2020
     */
    private Integer isSelected;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column review.create_time
     *
     * @mbg.generated Fri May 01 17:26:02 GMT+08:00 2020
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column review.update_time
     *
     * @mbg.generated Fri May 01 17:26:02 GMT+08:00 2020
     */
    private Date updateTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column review.comment_count
     *
     * @mbg.generated Fri May 01 17:26:02 GMT+08:00 2020
     */
    private Long commentCount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column review.like_count
     *
     * @mbg.generated Fri May 01 17:26:02 GMT+08:00 2020
     */
    private Long likeCount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column review.review_score
     *
     * @mbg.generated Fri May 01 17:26:02 GMT+08:00 2020
     */
    private Double reviewScore;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column review.creator
     *
     * @mbg.generated Fri May 01 17:26:02 GMT+08:00 2020
     */
    private Long creator;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column review.review_content
     *
     * @mbg.generated Fri May 01 17:26:02 GMT+08:00 2020
     */
    private String reviewContent;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column review.id
     *
     * @return the value of review.id
     *
     * @mbg.generated Fri May 01 17:26:02 GMT+08:00 2020
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column review.id
     *
     * @param id the value for review.id
     *
     * @mbg.generated Fri May 01 17:26:02 GMT+08:00 2020
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column review.user_id
     *
     * @return the value of review.user_id
     *
     * @mbg.generated Fri May 01 17:26:02 GMT+08:00 2020
     */
    public Long getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column review.user_id
     *
     * @param userId the value for review.user_id
     *
     * @mbg.generated Fri May 01 17:26:02 GMT+08:00 2020
     */
    public void setUserId(Long userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column review.movie_id
     *
     * @return the value of review.movie_id
     *
     * @mbg.generated Fri May 01 17:26:02 GMT+08:00 2020
     */
    public Long getMovieId() {
        return movieId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column review.movie_id
     *
     * @param movieId the value for review.movie_id
     *
     * @mbg.generated Fri May 01 17:26:02 GMT+08:00 2020
     */
    public void setMovieId(Long movieId) {
        this.movieId = movieId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column review.is_selected
     *
     * @return the value of review.is_selected
     *
     * @mbg.generated Fri May 01 17:26:02 GMT+08:00 2020
     */
    public Integer getIsSelected() {
        return isSelected;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column review.is_selected
     *
     * @param isSelected the value for review.is_selected
     *
     * @mbg.generated Fri May 01 17:26:02 GMT+08:00 2020
     */
    public void setIsSelected(Integer isSelected) {
        this.isSelected = isSelected;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column review.create_time
     *
     * @return the value of review.create_time
     *
     * @mbg.generated Fri May 01 17:26:02 GMT+08:00 2020
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column review.create_time
     *
     * @param createTime the value for review.create_time
     *
     * @mbg.generated Fri May 01 17:26:02 GMT+08:00 2020
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column review.update_time
     *
     * @return the value of review.update_time
     *
     * @mbg.generated Fri May 01 17:26:02 GMT+08:00 2020
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column review.update_time
     *
     * @param updateTime the value for review.update_time
     *
     * @mbg.generated Fri May 01 17:26:02 GMT+08:00 2020
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column review.comment_count
     *
     * @return the value of review.comment_count
     *
     * @mbg.generated Fri May 01 17:26:02 GMT+08:00 2020
     */
    public Long getCommentCount() {
        return commentCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column review.comment_count
     *
     * @param commentCount the value for review.comment_count
     *
     * @mbg.generated Fri May 01 17:26:02 GMT+08:00 2020
     */
    public void setCommentCount(Long commentCount) {
        this.commentCount = commentCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column review.like_count
     *
     * @return the value of review.like_count
     *
     * @mbg.generated Fri May 01 17:26:02 GMT+08:00 2020
     */
    public Long getLikeCount() {
        return likeCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column review.like_count
     *
     * @param likeCount the value for review.like_count
     *
     * @mbg.generated Fri May 01 17:26:02 GMT+08:00 2020
     */
    public void setLikeCount(Long likeCount) {
        this.likeCount = likeCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column review.review_score
     *
     * @return the value of review.review_score
     *
     * @mbg.generated Fri May 01 17:26:02 GMT+08:00 2020
     */
    public Double getReviewScore() {
        return reviewScore;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column review.review_score
     *
     * @param reviewScore the value for review.review_score
     *
     * @mbg.generated Fri May 01 17:26:02 GMT+08:00 2020
     */
    public void setReviewScore(Double reviewScore) {
        this.reviewScore = reviewScore;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column review.creator
     *
     * @return the value of review.creator
     *
     * @mbg.generated Fri May 01 17:26:02 GMT+08:00 2020
     */
    public Long getCreator() {
        return creator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column review.creator
     *
     * @param creator the value for review.creator
     *
     * @mbg.generated Fri May 01 17:26:02 GMT+08:00 2020
     */
    public void setCreator(Long creator) {
        this.creator = creator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column review.review_content
     *
     * @return the value of review.review_content
     *
     * @mbg.generated Fri May 01 17:26:02 GMT+08:00 2020
     */
    public String getReviewContent() {
        return reviewContent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column review.review_content
     *
     * @param reviewContent the value for review.review_content
     *
     * @mbg.generated Fri May 01 17:26:02 GMT+08:00 2020
     */
    public void setReviewContent(String reviewContent) {
        this.reviewContent = reviewContent == null ? null : reviewContent.trim();
    }
}